[package]
name = "zed_emmet"
version = "0.0.10"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
path = "src/emmet.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
