id = "emmet"
name = "Emmet"
description = "Emmet support"
version = "0.0.8"
schema_version = 1
authors = ["Piotr Osiewicz <piotr@zed.dev>"]
repository = "https://github.com/zed-extensions/emmet"

[language_servers.emmet-language-server]
name = "Emmet Language Server"
language = "HTML"
languages = ["HTML", "PHP", "Blade", "ERB", "HTML+ERB", "HTML/ERB", "JavaScript", "TSX", "CSS", "SCSS", "HEEX", "Elixir", "Vue.js", "Nunjucks", "Django"]

[language_servers.emmet-language-server.language_ids]
"HTML" = "html"
"PHP" = "php"
"Blade" = "blade"
"ERB" = "eruby"
"HTML/ERB" = "eruby"
"HTML+ERB" = "eruby"
"JavaScript" = "javascriptreact"
"TSX" = "typescriptreact"
"CSS" = "css"
"SCSS" = "scss"
"HEEX" = "heex"
"Elixir" = "heex"
"Vue.js" = "vue"
"Nunjucks" = "html"
"Django" = "html"
